language: node_js
node_js:
  - "12.7.0"

install:
  - npm install -g firebase-tools
  - npm install -g gatsby

script:
  - echo "Deploying"
  - gatsby build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
deploy:
  provider: firebase
  token:
    secure: "m47ZcSvJZPKNuE1chaMttw"
