language: node_js
node_js:
  - "12.7.0"

script:
  - echo "Deploying"

install:
  - npm install -g firebase-tools


after_success:
  - firebase deploy --token $FIREBASE_TOKEN
deploy:
  provider: firebase
  token:
    secure: "m47ZcSvJZPKNuE1chaMttw"
